`id` int NOT NULL AUTO_INCREMENT,
`person_name` varchar(500) DEFAULT NULL,
`person_number` varchar(500) DEFAULT NULL,
`box_name` varchar(500) DEFAULT NULL,
`shift` varchar(500) DEFAULT NULL,
`date_time` datetime DEFAULT NULL,
`hours` decimal(20,2) DEFAULT NULL,
`hourly_rate` decimal(20,2) DEFAULT NULL,
`total_amount` decimal(20,2) DEFAULT NULL,
`advanced_amount` decimal(20,2) DEFAULT NULL,
`remain_amount` decimal(20,2) DEFAULT NULL,
`booking_by` varchar(500) DEFAULT NULL,
`created_at` datetime DEFAULT NULL,
`updated_at` datetime DEFAULT NULL,